language: python
cache: pip

python:
  - "2.7"
  - "3.3"

before_script:
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then 2to3 -w -n --no-diffs . 2>&1 | tail -n 2; fi"

script:
  - nosetests

matrix:
  allow_failures:
    - python: "3.3"
